# Generated by Django 2.2.9 on 2020-01-23 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='websjite_url',
            new_name='website_url',
        ),
    ]
